apiVersion: v1
kind: Service
metadata:
  name: etcd
  labels:
    app: etcd
spec:
  ports:
    - port: 2380
      name: etcd-server
    - port: 2379
      name: etcd-client
  clusterIP: None
  selector:
    app: etcd
  publishNotReadyAddresses: true
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: etcd
  name: etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  serviceName: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      tolerations:
        - key: virtual-kubelet.io/provider
          operator: Exists
      schedulerName: virtual-kubelet
      containers:
        - name: etcd
          image: ccr.ccs.tencentyun.com/k8s-test/test:etcd-v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2380
              name: peer
              protocol: TCP
            - containerPort: 2379
              name: client
              protocol: TCP
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
#            - name: POD_IP
#              value: "10.0.2.15"
          command:
            - "./etcd"
            - "--name"
            - "infra0"
            - "--initial-advertise-peer-urls"
            - "http://${POD_IP}:2380"
            - "--listen-peer-urls"
            - "http://${POD_IP}:2380"
            - "--listen-client-urls"
            - "http://${POD_IP}:2379,http://127.0.0.1:2379"
            - "--advertise-client-urls"
            - "http://${POD_IP}:2379"
            - "--discovery"
            - "https://discovery.etcd.io/aee85dfbfabce34585346796f345d561"